### ISSUE TITLE
Getting error while migrating bosh manifest version v1 to manifest version v2

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/bosh-deployment#313] opened 2018-11-28 13:24 UTC
Hi,
We have following bosh director v1 manifest-deploy and running.
name: bosh
version: '261.4'
name: bosh-aws-cpi
version: '64'
name: stemcell
version: '3421.9'
we have upgraded bosh directory to 264 as bellow a with manifest file v1.
name: bosh
version: '264.7.0'
name: bosh-aws-cpi
version: '69'
name: stemcell
version: '3468.53'

Now we are upgrading bosh director manifest version2 using bosh-deployment repository: https://github.com/cloudfoundry/bosh-deployment/blob/v1.0.0/bosh.yml and also try from master branch.
but We are getting following error.
Task 2597 | 07:32:10 | Preparing deployment: Preparing deployment (00:00:00)
L Error: Existing instance 'bosh/0' is using IP '10.1.40.5' in availability zone ''
Task 2597 | 07:32:10 | Error: Existing instance 'bosh/0' is using IP '10.1.40.5' in availability zone ''
Exit code 1
Some Backgroud: in term of upgrading our bosh director and manifest file, we want to have same naming convenstion including ip address of bosh director.

Also analysing the following source code lines:
bosh/src/bosh-director/lib/bosh/director/deployment_plan/placement_planner/static_ips_availability_zone_picker.rb

Line 194 in 83b1650

 def assign_az_based_on_ip(desired_instance, existing_instance_model, network, ip_address) 
At L196- if ip_az_names.include?(existing_instance_model.availability_zone)
what we understood is that -> V1 bosh manifest file doesnt have any availability zones
whereas the V2 bosh leverage config and manifest file to upgrade it (via availability zones or is introduced )
Now how do we process - to pass the availability zone info in the manifest files or via which manifest file ?
I have attached bosh debug logs here.
[bosh-debug.txt](https://github.com/cloudfoundry/bosh-deployment/files/2624710/bosh-debug.txt)

**Comment by dpb587-pivotal** [comment] 2018-11-28 15:56
Closing - please avoid creating duplicate issues. This is a duplicate of https://github.com/cloudfoundry/bosh/issues/2082.

**Closed by dpb587-pivotal** 2018-11-28 15:56 UTC
Labels: unscheduled
