### ISSUE TITLE
Bosh deployment example for local provider has issues with credhub

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/bosh-deployment#222] opened 2018-03-27 11:16 UTC
When using the default bootstrap command, a director with the name 'Bosh Lite Director' is created. When you colocate Credhub this will lead to problems with creating credentials. An example can be seen here:
```bash
Task 32 | 10:59:46 | Preparing deployment: Preparing deployment (00:00:01)
                   L Error: Config Server failed to generate value for '/Bosh Lite Director/cf/diego_bbs_encryption_keys_passphrase' with type 'password'. HTTP Code '400', Error: 'Credential names may only include alpha, numeric, hyphen, underscore, and forward-slash characters. Please update and retry your request.'
```

A solution would be to change the documentation to use a bosh director name to bosh-lite-director, which is credhub-compatible.

**Comment by dpb587-pivotal** [comment] 2018-03-27 18:47
Agreed. Duplicate of https://github.com/cloudfoundry/docs-bosh/pull/392 and will check in on that one again.

**Closed by dpb587-pivotal** 2018-03-27 18:47 UTC
